spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/concertmania
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: concert-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: on

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-key: NzJrZC9vR2k2NTFIVVJxTkE3eWxPTUNrcGhpUHRPTmI=
  access-lifetime: 3600