spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  sql:
#    init:
#      schema-locations: db/schema.sql
#      mode: always
